controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

overblog_grphql_single_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/single.yaml"
    prefix: /graphql
